version: "3.8"

services:
  postgresdb:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgres
  streams_tech_test:
    depends_on:
      - postgresdb
    build: .
    restart: on-failure
    ports:
      - "8080:8080"
    volumes:
      - .m2:/root/.m2

volumes:
  db: