server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgresdb:5432/db
    username: root
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
      ddl-auto: create
